spring:
  datasource:
    url: jdbc:mysql://aa133mgwrmcnp37.ckmh1nerhtqr.us-east-1.rds.amazonaws.com:3306/ebdb?serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
    username: username
    password: password

  jpa:
    hibernate:
      ddl-auto: create
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB
      enabled: true
      file-size-threshold: 6MB
  profiles:
    active: @spring.profiles.active@

jwt:
  token:
    secret: jwtuser
    expired: 3600000

server:
  port: 6754

#Amazon S3
cloud:
  aws:
    credentials:
      access-key: AKIAYOZQ6BVH73C2TCA6
      secret-key: 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
    region:
      static: ap-southeast-1
    stack:
      auto: false
application:
  bucket:
    name: iflowerv1
