spring:
  datasource:
    url: jdbc:mysql://localhost:3306/flowers?serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
    username: bestuser
    password: bestuser

#    url: jdbc:mysql://aaculdcx2168y9.ckmh1nerhtqr.us-east-1.rds.amazonaws.com:3306/ebdb?serverTimezone=UTC
#    driver-class-name: com.mysql.jdbc.Driver
#    username: username
#    password: password
  jpa:
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB
      enabled: true
      file-size-threshold: 6MB

jwt:
  token:
    secret: jwtuser
    expired: 3600000000000000000

server:
  port: 6751

#Amazon S3
cloud:
  aws:
    credentials:
      access-key: AKIAYOZQ6BVH73C2TCA6
      secret-key: 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
    region:
      static: ap-southeast-1
    stack:
      auto: false
application:
  bucket:
    name: iflowerv1

price:
  distance: 2

#paypal
paypal:
  mode: sandbox
  client:
    id: ATIxHqdHjbPNxeO6eCTxA5xcqBADx7cfVkR18CN2kqw5E1vSK_5VjKlMnMTKzrzu9iDxpmgqaTRVGIFm
    secret: EPLfSdWbiOoWWK1OeKohvoas4ugfiA_F44Yp_gzpOrvUgUNyFYRYT4f_M5Hs0JnagvryaTkEXtHXE0B9
distance:
  matrix: AIzaSyAey_oEr5oWu84PmOLpU6GitUNWjy9bAKc
  from: Bishkek



